### ISSUE TITLE
Unfolding sections does not work on Chrome 88/Windows 10

### ISSUE THREAD

**Issue by st--** [st--/interactive-gp-visualization#4]
Pointed out by Jonas K. Lindeløv on [Twitter](https://twitter.com/jonaslindeloev/status/1399308309086224386).

**Comment by lindeloev** [comment]
There are no errors in the Chrome console, neither when I click to fold/collapse. When I click to unfold in Chrome 88, Windows 10 (and hence also in Edge), I get this error in the console and nothing happens:

```js
CollapsibleCard.svelte:48 Uncaught (in promise) ReferenceError: Cannot access 't' before initialization
    at CollapsibleCard.svelte:48
    at Generator.next (<anonymous>)
    at CollapsibleCard.svelte:1
    at new Promise (<anonymous>)
    at s (CollapsibleCard.svelte:1)
    at CollapsibleCard.svelte:65
    at g (CollapsibleCard.svelte:66)
    at HTMLDivElement.<anonymous> (CollapsibleCard.svelte:76)
(anonymous) @ CollapsibleCard.svelte:48
(anonymous) @ CollapsibleCard.svelte:1
s @ CollapsibleCard.svelte:1
(anonymous) @ CollapsibleCard.svelte:65
g @ CollapsibleCard.svelte:66
(anonymous) @ CollapsibleCard.svelte:76
```

Looks like the same error on Firefox:

```js
Uncaught (in promise) ReferenceError: can't access lexical declaration 't' before initialization
    g CollapsibleCard.svelte:48
    s CollapsibleCard.svelte:1
    s CollapsibleCard.svelte:1
    g CollapsibleCard.svelte:65
    g CollapsibleCard.svelte:66
    ct CollapsibleCard.svelte:76
    x index.mjs:238
    m CollapsibleCard.svelte:75
    tt index.mjs:1423
    m App.svelte:293
    tt index.mjs:1423
    nt index.mjs:1514
    <anonymous> main.ts:2
    app main.ts:2
    <anonymous> main.ts:3
CollapsibleCard.svelte:48:25
    s CollapsibleCard.svelte:1
    g CollapsibleCard.svelte:65
    g CollapsibleCard.svelte:66
    ct CollapsibleCard.svelte:76
    (Async: EventListener.handleEvent)
    x index.mjs:238
    m CollapsibleCard.svelte:75
    tt index.mjs:1423
    m App.svelte:293
    tt index.mjs:1423
    nt index.mjs:1514
    <anonymous> main.ts:2
    app main.ts:2
    <anonymous> main.ts:3
```

Is this specific to @rsdavis' Collapable Cards or this particular app? I'm on Chrome 88, Windows 10.

Again, your app looks a.w.e.s.o.m.e.! I may just finally understand GP, so I don't want to miss out on the fun ;-)

**Comment by rsdavis** [comment]
This is most likely because the app is using "svelte-collapsible-card" rather the newer "svelte-collapsible". The old package has since been deprecated in favor of the new one. This should be a simple change to make since the component interface hasn't change. The only difference is that you may want to specify the duration `<CollapsibleCard duration={0.2}>`.

Sorry for the confusion, let me know if there are any issues.

**Comment by st--** [comment]
@lindeloev the version deployed on my website is the "build" version which minifies the JS and hence leads to rather unhelpful error messages. You could clone & run locally, but even easier, instead:

Could you check whether you have any issues with [this Svelte REPL demo](https://svelte.dev/repl/7adc6bc2778040509ce498e6cb4322b0?version=3.30.0)?
That's based on the newer package @rsdavis mentioned and to which I will now transition.

Out of curiosity, could you also check if you can reproduce your original issue if in the REPL you replace the line
```diff
-    import { CollapsibleCard } from 'svelte-collapsible'
+    import { CollapsibleCard } from 'svelte-collapsible-card'
```
to use the (now deprecated) older package?

**Comment by st--** [comment]
@lindeloev fwiw, I've tried it out with Edge on Windows 10 and it all seems to work fine - both my full visualisation as well as the Svelte REPL demos of the collapsible cards (both deprecated and new package)..

**Comment by lindeloev** [comment]
Folding and unfolding works fine with svelete-collapsible. With svelte-collapsible-card, I get the error

> 'CollapsibleCard' is not exported by https://unpkg.com/svelte-collapsible-card@0.0.2/src/index.js, imported by ./App.svelte

Then I tried adding `duration = {0.2}` and removing the curly brackets, and now the demo seems to have crashed:

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

Maybe I should just stay far away and everything will work :-D

**Comment by st--** [comment]
@lindeloev I made the opposite mistake in my own code (fixed in f2f7f86c3bd7e94f16cdcd5fbdb9b89dbf176167), you actually need to replace
```diff
-    import { CollapsibleCard } from 'svelte-collapsible'
+    import CollapsibleCard from 'svelte-collapsible-card'
```
because the former exports multiple components in individual files, the latter only one through the main file. Can you try again with that? (Ignore the `duration` bit - that's just because rsdavis changed the default from 0.2 to 0.5 between packages, but shouldn't matter for your issue.)

I've also now updated the live version on http://infinitecuriosity.org/vizgp - can you check if upgrading my dependencies fixed it for you ?

**Comment by lindeloev** [comment]
It works! Great work. Closing.

**Comment by st--** [comment]
Great, glad that it was just a matter of moving away from a deprecated package : )
