### ISSUE TITLE
Variance of the sample points at x_1 seem to be higher than at x_2

### ISSUE THREAD

**Issue by mellorjc** [st--/interactive-gp-visualization#6]
Thanks for producing such a nice visualisation.

I'm using Chrome on Android.

When I look at where the 3 paths (green, blue, and orange) intersect with the red vertical line at x_1 as compared to where the same paths intersect the yellow vertical line at x_2, I observe a higher variance of the intersection points at x_1. This seems more pronounced when I move x_1 further from x_2.

Given I've not added any observations to the plot I was expecting the behaviour at both x_1 and x_2 to be symmetric. Have I missed something?

**Comment by st--** [comment]
Hi @mellorjc, thanks for the feedback:) In principle, the behaviour at x_1 and x_2 *is* symmetric (and indeed if you look at the code you should see the only difference is the variable names and the colour!). But you have to remember that the sample paths (green, blue, orange) are just a very small subset of *all* the possible samples. (Specifically, the sample paths are just great circles - so a very defined, not even a random subset - in the full N-dimensional sample space, where N is the number of evaluation points used to generate the plot.) So the variance of those three paths by themselves is meaningless - what you should consider is the behaviour if you click "Resample" many many times, and average over it. Does this explanation make sense ?

**Comment by mellorjc** [comment]
Thanks for the quick reply.
I guess I have not quite understood what the time component of the animation is conveying.

**Comment by st--** [comment]
Hi @mellorjc, I've now added more visualisation options - by default, it's now showing completely uncorrelated random samples (with cubic spline interpolation to make the transitions smooth) - have a look and hopefully that clears up your question:) If not, feel free to reopen this issue!

**Comment by mellorjc** [comment]
That's great. The dropdown list is enough to prompt me as to what I'm looking at. Thanks again for the great tool.
